services:
  warehouse:
    build: .
    container_name: ${CONTAINER_NAME:-warehouse}
    ports:
      - "${WEBDAV_PORT:-6065}:6065"
    volumes:
      - ${CONFIG_PATH:-./config.yml}:/config.yml:ro
      - ${DATA_PATH:-./data}:/data
      - ${LOGS_PATH:-./logs}:/logs
    env_file:
     - .env 
    command: -c /config.yml
